# Библиотека BLAS

Полезные ссылки:

https://docs.scipy.org/doc/scipy/reference/linalg.blas.html
https://www.math.utah.edu/software/lapack/#generalinformation
https://www.netlib.org/blas/
https://www.netlib.org/lapack/

Последние две ссылки могут не открываться без vpn

In [150]:
from scipy.linalg import blas
import numpy as np
import scipy as sp

In [21]:
n = 3
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[1,2,3],[4,5,6],[7,8,9]], order = 'F')

In [22]:
for cell in A.flatten():
    print(cell, end=' ')

print('\n')
    
for cell in B.flatten():
    print(cell, end=' ')

1 2 3 4 5 6 7 8 9 

1 2 3 4 5 6 7 8 9 

In [23]:
for x in np.nditer(A):
    print(x, end=' ')

1 2 3 4 5 6 7 8 9 

In [24]:
for x in np.nditer(B):
    print(x, end=' ')

1 4 7 2 5 8 3 6 9 

In [168]:
n = 4096
A = np.array(np.random.randn(n,n), order='F')
B = np.array(np.random.randn(n,n), order='F')

In [28]:
C_np = A @ B # numpy  C = A * B
C_blas = blas.dgemm(1.0, A, B) # BLAS C = A * B
np.linalg.norm(C_np - C_blas)

6.5909336550608786e-12

In [170]:
%timeit C_np = np.matmul(A,B) # numpy

1.92 s ± 155 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [169]:
%timeit C_blas = blas.dgemm(1.0, A, B) # blas

1.85 s ± 74.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [31]:
n = 4096
A = np.array(np.random.randn(n,n))
B = np.array(np.random.randn(n,n))

In [32]:
C_blas = blas.dgemm(1.0, A, B)
print(C_blas)

[[  32.03555559  127.94738428    8.28070363 ...  -70.77253561
   128.14473562    9.32390935]
 [ -15.960679   -104.7011489    17.37997408 ...   89.80863209
    28.53518697  -78.24360485]
 [ -30.03495269  -73.52294898  -66.39684318 ...  -62.90966927
   -10.8076485    -7.3370816 ]
 ...
 [   3.13818585   55.97067653   28.69951213 ...   82.34773448
    81.45329612    0.3814714 ]
 [  -3.01720301  -62.16570239   15.12528832 ...   32.830196
   -15.64879037   26.6734063 ]
 [   0.48407073   78.68721623   17.68816809 ...  -75.1954028
   -43.20803461   -1.11043817]]


In [58]:
def MatrMul(A,B,n):
    
    result = np.zeros((n,n))
    for i in range(n):  
        for j in range(n):
            for k in range(len(B)):
                result[i][j] += A[i][k] * B[k][j]
                
    return result

In [63]:
A = np.array([[1,1],[1,2]], order = 'F')
B = np.array([[2,-1],[0,1]], order = 'F')
C = MatrMul(A,B,2)
print(A)
print(B)
print(C)

[[1 1]
 [1 2]]
[[ 2 -1]
 [ 0  1]]
[[2. 0.]
 [2. 1.]]


In [190]:
n = 100
A = np.array(np.random.randn(n,n), order = 'F')
B = np.array(np.random.randn(n,n), order = 'F')

Попробуйте убрать *order = 'F'* и сравните время 

In [192]:
%timeit C_blas = blas.dgemm(1.0, A, B) # blas

34.3 µs ± 1.26 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [77]:
%timeit C_our = MatrMul(A,B,n) # our

882 ms ± 21.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


**Названия функций в BLAS и LAPACK**

blas.<точность><имя><объкты>

<точность>:

s: single precision float

d: double precision float

c: single precision complex float

z: double precision complex float


<имя> - тип операции или матрицы 

<объкты> - используемые объекты или информация об операции

Пример:
dgemm = d + ge + mm 
d - double precision, ge - general matrix, mm - matrix multiplication

# BLAS Level 1

Операции вектор-вектор, число-вектор

**_axpy** - операция вычисления *ax + y* (x,y - векторы, a - скаляр)

**_dot** - скалярное произведение

**_nrm2** - евклидова норма

## _axpy

In [78]:
n = 1000
x = np.random.rand(n)
y = np.random.rand(n)

z = blas.daxpy(x, y, a=1.0)
xx = blas.ddot(x, x)
x2 = blas.dnrm2(x)
np.sqrt(xx) - x2

0.0

In [96]:
x = np.array([1,2,3])
y = np.array([1,1,1])    
z = blas.daxpy(x, y, a=1.0)
print(z)

[2. 3. 4.]


In [95]:
x + y

array([2, 3, 4])

In [99]:
x = np.array([1,2,3])
y = np.array([[1],[1],[1]])    
z = blas.daxpy(x, y, a=2.0)
print(z)

[[3.]
 [5.]
 [7.]]


In [100]:
x + y

array([[2, 3, 4],
       [2, 3, 4],
       [2, 3, 4]])

## _dot

In [131]:
x = np.array([1,2,3]) #try  [[1],[2],[3]]
y = np.array([2,1,1]) #try  [[2],[1],[1]]   
z = blas.ddot(x, y)
print(z)

7.0


https://numpy.org/doc/stable/reference/generated/numpy.dot.html

In [132]:
z = np.dot(x, y)
print(z)

7


In [135]:
n = 5000
x = np.random.rand(n)
y = np.random.rand(n)

In [144]:
%timeit z = blas.ddot(x, y)

1.59 µs ± 40.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [142]:
%timeit z = np.dot(x, y)

3.3 µs ± 95.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [143]:
%timeit z = np.vdot(x, y)

3.22 µs ± 70.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
%timeit z = np.vdot(x, y)

Обратите внимание на разницу *cdotu* и *cdotc* в документации

## _nrm2

In [157]:
x = np.array([2,-2,1])  #try [[2],[-2],[1]]

xn = blas.dnrm2(x)
print(xn)

3.0


numpy.linalg.norm

https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html   

scipy.linangl

https://docs.scipy.org/doc/scipy/reference/linalg.html

In [158]:
xn = sp.linalg.norm(x)
print(xn)
xn = np.linalg.norm(x)
print(xn)

3.0
3.0


In [162]:
n = 5000
x = np.random.rand(n)

In [160]:
%timeit xn = blas.dnrm2(x)

1.8 µs ± 95.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [165]:
%timeit xn = sp.linalg.norm(x)

8.73 µs ± 155 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [164]:
%timeit xn = np.linalg.norm(x)

7.37 µs ± 646 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# BLAS Level 2

Операции матрица-вектор

**_gemv** - умножение матрицы на вектор и скаляр:  *aAx* (a - скаляр, A - матрица, x - вектор)

**_trmv** - умножение треугольной матрицы на вектор: *Lx*

**_trsv** - решение СЛАУ с нижней треугольной матрицей: *inv(L)x*



## _gemv

In [222]:
x = np.array([[2],[1]])  # try [[2],[1]]
A = np.array([[-1,1],[3,2]])
alfa = 2.0

y = blas.dgemv(alfa,A,x)
print(y)

[-2. 16.]


## _trmv

In [229]:
x = np.array([2,1])  # try [[2],[1]]
A = np.array([[-1,3],[1,2]])

y = blas.dtrmv(A,x, lower = 0)
print(y)

[1. 2.]


## _trsv

In [234]:
x = np.array([2,1])  # try [[2],[1]]
A = np.array([[-1,3],[1,2]])

y = blas.dtrsv(A,x, lower = 1)
print(y)

[-2.   1.5]
