# Собственные значения

Функция eig

In [14]:
import numpy as np
import scipy.linalg as sla

A = np.array([[5, 6, 3],[-1, 0, 1], [1, 2, -1]])
print(A)
print('\n')

evalues,evectors = sla.eig(A)

print(evalues)
print(evectors)


[[ 5  6  3]
 [-1  0  1]
 [ 1  2 -1]]


[-2.+0.j  4.+0.j  2.+0.j]
[[-3.26843061e-16 -9.70494959e-01 -8.94427191e-01]
 [-4.47213595e-01  2.15665546e-01  4.47213595e-01]
 [ 8.94427191e-01 -1.07832773e-01  2.41495254e-16]]


In [2]:
P = evectors[:,0]
P

array([ 0.81649658,  0.40824829, -0.40824829])

In [3]:
n = 100
A = np.array(np.random.randn(n,n))

In [4]:
%timeit evalues,evectors = sla.eig(A) 

3.2 ms ± 148 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [16]:
A = np.array([[5, 6, 3],[-1, 0, 1], [1, 2, -1]])
X = np.array([[1],[1],[1]])

m = 0
while (m < 10):
    X = A@X
    X = X/sla.norm(X)
    m = m + 1
    
print(X)

Y = A@X
Y = Y/sla.norm(Y)
print(Y)


if (Y[0]*X[0] < 0):
    Y = np.multiply(Y,-1)
Y = np.subtract(X, Y)
print("diff norm:", sla.norm(Y))

[[ 0.97052067]
 [-0.21547804]
 [ 0.10797616]]
[[ 0.97051884]
 [-0.21554794]
 [ 0.10785299]]
diff norm: 0.0001416373270551295


In [11]:
n = 200
A = np.array(np.random.randn(n,n))
A = (A + A.T)/2

X = np.array([0]*n)
X[0]=1


m = 0
while (m < 100):
    X = A@X
    X = X/sla.norm(X)
    m = m + 1
    
Y = A@X
Y = Y/sla.norm(Y)
if (Y[0]*X[0] < 0):
    Y = np.multiply(Y,-1)
Y = np.subtract(X, Y)
print("diff norm:", sla.norm(Y))


diff norm: 0.0029785324755029156
