# Пример - вычисление собственных значений

In [1]:
import numpy as np 
import scipy.linalg as la 

A = np.array([[1., 1000], [0, 1]])
B = np.array([[1, 1000], [0.001, 1]])

print(A)

print(B)

[[   1. 1000.]
 [   0.    1.]]
[[1.e+00 1.e+03]
 [1.e-03 1.e+00]]


In [2]:
np.set_printoptions(suppress=True, precision=8)

In [3]:
wA, vrA = la.eig(A)
wB, vrB = la.eig(B)

wA, wB

(array([1.+0.j, 1.+0.j]), array([ 2.+0.j, -0.+0.j]))

In [5]:
vrB

array([[ 0.9999995, -0.9999995],
       [ 0.001    ,  0.001    ]])