Практика 5.
Написать функцию, которая решает СЛАУ Ax=b методом ортогонализации по строкам.
Использовать библиотеку BLAS для всех операций с векторами.
Для справки: см. сборник задач по вычислительной математике под ред. Демченко.

# QR разложение

In [41]:
import numpy as np
import scipy.linalg as sla
from scipy.linalg import blas
from math import sqrt

In [59]:
def SO(A, b):

    # Check shape of A
    if (A.shape[0] > A.shape[1]):
        print("A must have more cols than rows for SO")
        return

    m = A.shape[0]
    n = A.shape[1]

    C = np.zeros((m,n))
    d = np.zeros(n)

    scalar = blas.ddot(A[0, :], A[0, :])
    c_current = A[0, :] / sqrt(scalar)
    d_current = b[0] / sqrt(scalar)
    C[0, :] = c_current
    d[0] = d_current
    
    for i in range(1, m):
        sum = 0
        sum2 = np.zeros(m)
        for j in range (0, i):
            sum = sum + blas.ddot(A[i, :], C[j, :]) * d[j]
            sum2 = sum2 + blas.ddot(A[i, :], C[j, :]) * C[j, :]
        c_current = A[i, :] - sum2
        scalar = blas.ddot(c_current, c_current)
        c_current = c_current / sqrt(scalar)
        d_current = (b[i] - sum) / sqrt(scalar)
        C[i, :] = c_current
        d[i] = d_current

    return blas.dgemm(1.0, C, d, trans_a=1)



In [78]:
n = 3
A = np.array([[1,-1,2],[0,2,4],[2,1,-1]])
b = np.array([-2, -2, 4])
x = SO(A, b)
print(A)
print(x)

[[ 1 -1  2]
 [ 0  2  4]
 [ 2  1 -1]]
[[ 1.]
 [ 1.]
 [-1.]]


In [80]:
n = 2000
A = np.array(np.random.randn(n,n), order='F')
b = np.array(np.random.randn(n))

In [81]:
x = SO(A, b)
print(x)

[[ 0.3765862 ]
 [-0.95758173]
 [ 0.2001382 ]
 ...
 [ 0.29893073]
 [-0.23227993]
 [ 0.11129534]]


In [82]:
print(np.linalg.solve(A, b))

[ 0.3765862  -0.95758173  0.2001382  ...  0.29893073 -0.23227993
  0.11129534]
